image: registry.sensetime.com/zoetrope/pytorch:1.7.0-cuda11.0-cudnn8-devel-ffmpeg4

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - python --version
  - pip --version
  - nvcc --version
  - nvidia-smi
  - python -c "import torch; print(torch.__version__)"
  - ffmpeg -version

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort==4.3.21
    - flake8 .
    - isort -rc --check-only --diff mmhuman3d/ tools/ tests/
    - yapf -r -d mmhuman3d/ tools/ tests/ configs/

test:
  stage: test
  script:
    - echo "Start building..."
    - pip install opencv-python-headless
    - pip install -e .
    - python -c "import mmhuman3d; print(mmhuman3d.__version__)"
    - echo "Start testing..."
    - pip install pytest coverage
    - coverage run --source mmhuman3d -m pytest tests/
    - coverage report -m
