image: registry.sensetime.com/zoetrope/pytorch:1.7.0-cuda11.0-cudnn8-devel-ffmpeg4-smpl

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - python --version
  - pip --version
  - nvcc --version
  - nvidia-smi
  - python -c "import torch; print(torch.__version__)"
  - ffmpeg -version
  - export http_proxy=http://172.16.1.135:3128/
  - export https_proxy=http://172.16.1.135:3128/
  - export HTTP_PROXY=http://172.16.1.135:3128/
  - export HTTPS_PROXY=http://172.16.1.135:3128/

linting:
  stage: linting
  script:
    - pip install interrogate
    - apt update && apt install curl libyaml-dev git -y
    - curl -L https://get.rvm.io | bash -s -- --autolibs=read-fail
    - source /etc/profile.d/rvm.sh
    - rvm autolibs disable
    - rvm install 2.7.1
    - pip install pre-commit
    - pre-commit install
    - pre-commit run --all-files --verbose
    - echo "Docstring coverage results:"
    - interrogate -vinmMI -f 50 mmhuman3d/

test:
  stage: test
  tags:
    - gpu
  script:
    - echo "Start building..."
    - pip install opencv-python-headless
    - pip install h5py tqdm
    - conda install -c conda-forge xorg-libx11
    - pip install vedo numpy scipy
    - pip install -e .
    - python -c "import mmhuman3d; print(mmhuman3d.__version__)"
    - echo "Start testing..."
    - cp -r /workspace/data/body_models ./body_models
    - pip install pytest coverage
    - coverage run --source mmhuman3d -m pytest tests/
    - coverage report -m
